import QueryProvider from "@/components/QueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { initializeMixedContent } from "../../meta-config";
import "../globals.css";

initializeMixedContent();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://your-production-site-url.com"),
  title: "Asiri Auto Wheels",
  description: "Generated by create next app",
  openGraph: {
    images: "/images/Logo.jpeg",
  },
  twitter: {
    images: "/images/Logo.jpeg",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
