import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://your-production-site-url.com"),
  title: "Asiri Auto Wheels",
  description: "Generated by create next app",
  openGraph: {
    images: "/images/Logo.jpeg",
  },
  twitter: {
    images: "/images/Logo.jpeg",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-screen">
      {/* Side Navigation + Content */}
      <div className="flex overflow-hidden grow">
        {/* Side Navigation */}
        <Navbar />
        {/* Content */}
        <div
          className={`flex w-full rounded bg-muted duration-300 transition-all  lg:ms-[280px] : ms-0 p-3 lg:p-5`}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
